server:
  port: 9090

management:
  context-path: /admin

mqtt:
  url: tcp://pi3:1883
  publish:clientid: sdrconnectorpub
  subscribe:clientid: sdrconnectorsub

adsb:
  mongodb:
    collection: positionData
  mqtt:
    inbound-topic: adsb/input
    outbound-topic: adsb/output

spring:
  jackson:
    deserialization:
      use_long_for_ints: true
  data:
    mongodb:
      database: adsbmonitor
      host: ""