server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  data:
    mongodb:
      database: adsbmonitor
  jackson:
    serialization:
      indent_output: true
