server:
  port: 8080

management:
  context-path: /admin
spring:
  data:
    mongodb:
      database: adsbmonitor

spring:
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
